### ISSUE TITLE
Lesser Efreeti and Shred of Darkness - death animation

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1007]
in love, carcass is shown on death by explosive attacks and instakills.
their own death animation should be used.
![2019_11_24_16_34_36_228_new - 1533](https://user-images.githubusercontent.com/43391939/69491600-b7f27100-0eda-11ea-933c-dab8c13a7c1f.jpg)

**Comment by cigumo** [comment]
fixed in kr2-desktop-3.2.12

**Comment by sunnydaler** [comment]
shred of darkness in desktop-3.2.13; not fixed for instakill. (Lesser Efreeti is fixed)
![desktop-3 2 13](https://user-images.githubusercontent.com/43391939/70515402-a1097b00-1b78-11ea-8cf1-c763e1c4ae7e.gif)

**Comment by cigumo** [comment]
fixed in kr2-x-3.2.16
