### ISSUE TITLE
Stunned avenger will have high armor even while melee blocked / VirtualTT

### ISSUE THREAD

**Issue by cigumo** [cigumo/krli#489]
> Immobilized twilight avenger (e.g. sleeping) will have High armor even if he is currently engaged in melee battle

**Comment by cigumo** [comment]
fixed in 1.2.0

**Comment by sunnydaler** [comment]
not fixed in 1.2.1
Steam https://streamable.com/1p65i
mobile https://streamable.com/9jgt8

**Comment by sunnydaler** [comment]
I checked catha's sleep, denas's celebrity, weirdwood's clobber, slumber arrows, veznan's demon, and Xin on Steam.
and the results are the same; not fixed.

**Comment by cigumo** [comment]
I modified it in 1.2.5 to drop to unshielded when stunned.
